---
- name: Deploy NVIDIA GPU Operator
  hosts: localhost
  connection: local
  tasks:
    - name: Create NVIDIA GPU Operator Namespace
      kubernetes:
        kind: Namespace
        name: nvidia-gpu-operator
        state: present

    - name: Create NVIDIA GPU Operator Subscription
      kubernetes:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: gpu-operator-certified
            namespace: nvidia-gpu-operator
          spec:
            channel: stable
            name: gpu-operator-certified
            source: certified-operators
            sourceNamespace: openshift-marketplace

    - name: Wait for NVIDIA GPU Operator to be ready
      kubernetes:
        kind: ClusterServiceVersion
        name: gpu-operator-certified.v1.10.1
        namespace: nvidia-gpu-operator
        wait: yes
        wait_timeout: 300
