apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig/operatorgroup.yaml

namespace: gpu-operator-resources

resources:
- gpu-operator-resources-namespace.yaml
- gpu-operator-subscription.yaml
- gpu-operator-operatorgroup.yaml
- gpu-operator-configmap.yaml

vars:
- name: NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: gpu-operator-config
  fieldref:
    fieldPath: data.NAMESPACE
