---
- name: Deploy NFD Instance
  hosts: localhost
  connection: local
  tasks:
    - name: Create NFD Instance
      kubernetes:
        definition:
          apiVersion: nfd.openshift.io/v1
          kind: NodeFeatureDiscovery
          metadata:
            name: nfd-instance
            namespace: openshift-nfd
          spec:
            operand:
              image: registry.redhat.io/openshift4/ose-node-feature-discovery:v4.9
            workerConfig:
              configData: |
                sources:
                  pci:
                    deviceClassWhitelist:
                      - "0300"
